APP_NAME = "Easy Overlay"
ORGANIZATION_NAME = "Aijiuaihai"

WINDOW_SIZE = 128
MIN_CROSSHAIR_ARM_LENGTH = 1
DEFAULT_CROSSHAIR_ARM_LENGTH = 44
DEFAULT_CROSSHAIR_GAP = 7
DEFAULT_CROSSHAIR_THICKNESS = 3
DEFAULT_CROSSHAIR_OUTLINE_THICKNESS = 7
